use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Order {
    pub order_uid: String,
    pub track_number: Option<String>,
    pub entry: Option<String>,
    pub delivery_name: Option<String>,
    pub delivery_phone: Option<String>,
    pub delivery_zip: Option<String>,
    pub delivery_city: Option<String>,
    pub delivery_address: Option<String>,
    pub delivery_region: Option<String>,
    pub delivery_email: Option<String>,
    pub payment_transaction: Option<String>,
    pub payment_request_id: Option<String>,
    pub payment_currency: Option<String>,
    pub payment_provider: Option<String>,
    pub payment_amount: Option<i32>,
    pub payment_payment_dt: Option<i64>,
    pub payment_bank: Option<String>,
    pub payment_delivery_cost: Option<i32>,
    pub payment_goods_total: Option<i32>,
    pub payment_custom_fee: Option<i32>,
    pub items_chrt_id: Option<i32>,
    pub items_track_number: Option<String>,
    pub items_price: Option<f64>,
    pub items_rid: Option<String>,
    pub items_name: Option<String>,
    pub items_sale: Option<i32>,
    pub items_size: Option<String>,
    pub items_total_price: Option<f64>,
    pub items_nm_id: Option<i32>,
    pub items_brand: Option<String>,
    pub items_status: Option<i32>,
    pub locale: Option<String>,
    pub internal_signature: Option<String>,
    pub customer_id: Option<String>,
    pub delivery_service: Option<String>,
    pub shardkey: Option<String>,
    pub sm_id: Option<i32>,
    pub date_created: Option<String>,
    pub oof_shard: Option<String>,
}
